//go:build !noasm && amd64
// Code generated by gocc -- DO NOT EDIT.

package bitmap

import "unsafe"

//go:noescape
func _and_avx512(a []uint64, b []uint64)

//go:noescape
func _andn_avx512(a []uint64, b []uint64)

//go:noescape
func _or_avx512(a []uint64, b []uint64)

//go:noescape
func _xor_avx512(a []uint64, b []uint64)

//go:noescape
func _and_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape
func _andn_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape
func _or_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape
func _xor_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape
func _count_avx512(a []uint64) uint64
